# Welcome to Jekyll!

# Website settings
title: "Sauraus"
description: "Sauraus -- Cevi Festival 2017"
keywords: "Cevi, Cevi Region Bern, Festival, Leiterevent, Sauraus"
baseurl: "/"
url: "http://sauraus.ch"

# blog img path
img_path: 'http://sauraus.ch/static/img/blog'

# author
author:
  name: 'Yakin'
  first_name: 'Jonas'
  last_name: 'Wagner'
  email: 'yakin@cevi.ch'
  facebook_username: 'Sjlver'
  github_username: 'Sjlver'
  head_img: 'static/img/landing/Yakin.jpg'

# social link
#jingyu:
#  first_name: 'Yu'
#  last_name: 'Jing'
#  description: 'Painter.'
#  link: 'http://angular.jack003.com'
#  email: '805963294@qq.com'

# landing page
landing:
  home: 'Home'
  about: 'Über uns'
  what_where: 'Was&Wo'
  program: 'Programm'
  blog: 'Blog'
  link: 'Links'

# blog index
index:
  home: 'Home'
  blog: 'Blog'

# donate
donate:
#  wechat: 'static/img/pay/wechat.png'
#  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: cysfY7ULn
  # conf: prod_861928934cecb7a18e15bedaed9dae29
disqus:
#  name: jalpc
#  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# share
bshare:
#  uuid: 513f778e-a8f7-4c20-9ec2-d29cc2328d75

# baidu analytics
ba:
#  uuid: 317acca9ef9255b934e46371e471431d

# google analytics
ga:
#  id: UA-73784599-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
