# Welcome to Jekyll!

# Website settings
title: "Sauraus"
description: "Sauraus -- Cevi Festival 2017"
keywords: "Cevi, Cevi Region Bern, Festival, Leiterevent, Sauraus"
baseurl: "/"
url: "http://sauraus.ch"

# blog img path
img_path: 'http://sauraus.ch/static/img/blog'

# author
author:
  name: 'Yakin'
  first_name: 'Jonas'
  last_name: 'Wagner'
  email: 'yakin@cevi.ch'
  facebook_username: 'Sjlver'
  github_username: 'Sjlver'
  head_img: 'static/img/landing/Yakin.jpg'

# landing page
landing:
  home: 'Home'
  about: 'Über uns'
  pictures: 'Bilder'
  what_where: 'Was&Wo'
  register: 'Anmelden'
  program: 'Programm'
  blog: 'Blog'
  link: 'Links'

# blog index
index:
  home: 'Home'
  blog: 'Blog'

disqus:
#  name: jalpc
#  public_key: tj2MPaNlHMONwTH5bGDNSXyaBpW7q282MeUzh5CwcjJerNhK8Kxk3aWo7IckzTX7

# google analytics
ga:
  id: UA-84705254-1

#Jekyll-Photo-Gallery Settings
exiftag:
  sources:
    - images/photography #Set to location of photos

#MiniMagick
#https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography:
        source: images/photography
        destination: images/photography/thumbnails
        resize: "1280x720"
    headers:
        source: images/headers
        destination: images/headers/thumbnails
        resize: "400x250"

# other settings
encoding: "utf-8"
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
gems:
  - jekyll-assets
